[phases.setup]
nixPkgs = ["nodejs", "python3", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = [
    "mkdir -p /usr/local/bin",
    "ln -s $(which python3) /usr/local/bin/python || true",
    "npm ci"
]

[start]
cmd = "node api/index.js"
